willbasky/hibet

.gitignore, CHANGELOG.md, app/Main.hs, src/Tibet.hs
Resolves [#4](https://github.com/willbasky/TibetCli/issues/4)
=> [#4] Fix output delay

src/Handlers.hs, src/Tibet.hs, tibet.cabal
Resolves [#7](https://github.com/willbasky/TibetCli/issues/7)
Resolves [#8](https://github.com/willbasky/TibetCli/issues/8)
=> [#8] Show values of duplicate keys

CHANGELOG.md, src/Handlers.hs, src/Tibet.hs, stack.yaml, tibet.cabal
Resolves [#2](https://github.com/willbasky/TibetCli/issues/2)
=> [#2] Look up through all libriries

CHANGELOG.md, README.md, src/Handlers.hs, src/Tibet.hs
Resolves [#14](https://github.com/willbasky/TibetCli/issues/14)
=> [#14] show dictionary title

CHANGELOG.md, README.md, src/Handlers.hs, src/Tibet.hs
Resolves [#6](https://github.com/willbasky/TibetCli/issues/6).
Resolves [#18](https://github.com/willbasky/TibetCli/issues/18).
Move back to `Strict Texts`.
And some refactoring.
=> [#6] Search diractly in raw dictionares.

CHANGELOG.md, app/Main.hs, src/Cli.hs, src/Handlers.hs, src/Sandbox.hs, src/Tibet.hs, tibet.cabal
Resolves [#28](https://github.com/willbasky/TibetCli/issues/28)
=> [#28] Hold HashMap dictionary in memory

CHANGELOG.md, src/Handlers.hs, src/Sandbox.hs
Resolve [#22](https://github.com/willbasky/TibetCli/issues/22)
=> [#22] Create HashMap without dublicate values

CHANGELOG.md, src/Handlers.hs, src/Sandbox.hs, src/Tibet.hs
Just for reduce memory using. From 327 Mb to 186 Mb.
=> Move to ByteString

CHANGELOG.md, src/Cli.hs
Resolves [#32](https://github.com/willbasky/TibetCli/issues/32)
=> [#32] Add  'om' command

CHANGELOG.md, README.md, src/Handlers.hs, src/Labels.hs, src/Tibet.hs, tibet.cabal
Resolve [#40](https://github.com/willbasky/TibetCli/issues/40)
=> Add history state and ':h' command to show it

CHANGELOG.md, src/Cli.hs, tibet.cabal
Resolves [#25](https://github.com/willbasky/TibetCli/issues/25)
=> [#25] Show one dictionary description

CHANGELOG.md, src/Cli.hs, src/Handlers.hs, src/Tibet.hs, tibet.cabal
=> Select dicts by id

src/Labels.hs
=> Fix meta sort

CHANGELOG.md, README.md
=> [#49] Add video of usage

benchmark/Main.hs, src/Handlers.hs, tibet.cabal
Streamly has not lines, span functions. Benchmark shows streamly is worst. May be there is way to implement better, I don't know yet.
=> Bench streamly

.gitignore, .hlint.yaml, CHANGELOG.md, src/Cli.hs, src/Sandbox.hs, src/Tibet.hs, tibet.cabal
Resolve #54 
Made with [haskeline](https://hackage.haskell.org/package/haskeline-0.7.5.0). 
Besides Up/Down keys [other keys](https://github.com/judah/haskeline/wiki/KeyBindings#commands-shared-by-both-bindings) begun to work.
=> Fix up/down keys

CHANGELOG.md, src/Parse.hs, src/Tibet.hs
Resolve [#57]
```
Which a tibetan word to translate?
> མི
mi
2. Gäng / Wetzel
► human
Sanskrit: manuṣyaḥ
Pali: manusso
...
```
=> Consume tibetan input

LICENSE
=> Swap mit with gpl3 license

.travis.yml, benchmark/Main.hs, src/Labels.hs
Resolves #80
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/willbasky/hibet/81)
=> Add hlint check (#80)

.gitignore, CHANGELOG.md, benchmark/Assets.hs, benchmark/Main.hs, hibet.cabal, src/App.hs, src/Labels.hs, stack.yaml, stack.yaml.lock
Refactor configs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/willbasky/hibet/87)
=> Check file embeded

src/App.hs, src/Env.hs, src/Utility.hs, test/env/Main.hs
Resolve #103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/willbasky/hibet/105)
=> Add traces

CHANGELOG.md, src/App.hs, src/Cli.hs
Resolve #104 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/willbasky/hibet/108)
=> [#104] Add Input from polysemy

CHANGELOG.md, hibet.cabal, src/App.hs, src/Cli.hs, src/Dictionary.hs, src/Effects/File.hs, src/Effects/PrettyPrint.hs, src/Env.hs, src/Label.hs, src/Parse.hs, src/Translator.hs, src/Type.hs, src/Utility.hs, stack.yaml, stack.yaml.lock, test/env/Main.hs
Update polysemy deps. 
Land syllables on bimap.
Selection of dictionaries on launch not works yet. It wanted Reader
Resolves #109 
Resolves #110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/willbasky/hibet/112)
=> Get rid of parsers-megaparsec. 

src/App.hs, src/Cli.hs, src/Translator.hs
Recover dictionary selection feature
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/willbasky/hibet/114)
=> Swap Input with Reader sem. 

CHANGELOG.md, benchmark/Main.hs, hibet.cabal, src/Cli.hs, src/Parse.hs, src/Parse/SyllableLines.hs, src/Parse/TibetanWord.hs, src/Parse/Type.hs, src/Parse/WylieText.hs, src/Parse/WylieWord.hs, src/Pretty.hs, src/Translator.hs, src/Type.hs, src/Utility.hs, stack.yaml, test/env/Main.hs, test/env/Paths.hs, test/env/data/dicts/Berzin-T|E.txt, test/env/data/dicts/Hopkins-2015-T|E.txt, test/env/data/stuff/titles.toml, test/parse/Main.hs
=> Fix wylie parse bug

CHANGELOG.md, hibet.cabal, src/App.hs, src/Cli.hs, src/Translator.hs, stack.yaml
=> Make Env concurrently

CHANGELOG.md, benchmark/Lines.hs, cabal.project, hibet.cabal, src/Effects/Console.hs, src/Effects/File.hs, src/Env.hs, src/Parse.hs, src/Parse/SyllableLines.hs, src/Type.hs, stack.yaml, test/env/Main.hs
It is just outdated wrapper. I need just one function from there
Resolve #135
=> Get rid of Polysemy-path

.github/workflows/haskell-ci.yml, CHANGELOG.md, README.md, hibet.cabal, stack.yaml
=> Add building support of ghc924
